version: '3'
services:
  node:
    container_name: node
    restart: always
    image: node:14.17
    build: .
    ports:
      - '80:3000'
    links:
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: talentlab
      POSTGRES_USER: talentlab
      POSTGRES_PASSWORD: talentlab
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
